### ISSUE TITLE
Running ARM FS with Ruby

### ISSUE THREAD

**Issue by z3ky** [tukl-msd/gem5.bare-metal#1]
Trying to run the bare-metal example with --ruby ended in the following error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ericwagner/gem5/src/python/m5/main.py", line 400, in main
    exec filecode in scope
  File "./configs/example/fs.py", line 341, in <module>
    test_sys = build_test_system(np)
  File "./configs/example/fs.py", line 103, in build_test_system
    ruby=options.ruby)
  File "/Users/ericwagner/gem5/configs/common/FSConfig.py", line 374, in makeArmSystem
    self.realview.attachOnChipIO(self.iobus, dma_ports=self._dma_ports)
TypeError: attachOnChipIO() got an unexpected keyword argument 'dma_ports'

**Comment by myzinsky** [comment]
I'm not sure if this bug is related to this bare-metal example. As far as I know, the ruby model should not be used, its better to use the classic memory model. However, if you could find out whats going wrong let me know and I will fix it, or you can also do a pull request. 

Thanks,
Matthias
